// frontend/src/components/UnifiedTypeSelector.tsx
/**
 * UnifiedTypeSelector - 统一类型选择器 (React 版本)
 * 
 * 设计原则（来自 type-selector-design.md）：
 * 1. 构建面板始终可见：显示当前类型结构，支持嵌套可视化
 * 2. 选择面板复用：点击任意可编辑部分（▼）时显示同一个选择器
 * 3. 约束类型支持：AnyType、AnyFloat 等约束可作为类型使用
 * 4. 包装选项统一：在选择面板中提供 +tensor、+vector 等包装入口
 * 5. 方言分组：内置约束/类型 + 方言特有约束分组显示
 * 
 * 数据逻辑已抽取到 typeSelectorService.ts，本组件只负责渲染
 */

import { memo, useCallback, useMemo, useRef, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { getTypeColor } from '../services/typeSystem';
import { useTypeConstraintStore } from '../stores/typeConstraintStore';
import {
  type TypeNode,
  type WrapperInfo,
  WRAPPERS,
  serializeType,
  parseType,
  wrapWith,
} from '../services/typeNodeUtils';
import {
  type SearchFilter,
  computeTypeSelectorData,
  computeTypeGroups,
  hasConstraintLimit,
} from '../services/typeSelectorService';

// ============ 选择面板组件 ============

interface SelectionPanelProps {
  position: { top: number; left: number };
  currentValue: string;
  onSelect: (value: string) => void;
  onWrap: (wrapper: string) => void;
  onClose: () => void;
  panelRef: React.RefObject<HTMLDivElement | null>;
  /** 约束对应的具体类型列表，null 表示无约束 */
  constraintTypes: string[] | null;
  /** 允许的包装器列表 */
  allowedWrappers: readonly WrapperInfo[];
  /** 原始约束名（用于显示） */
  constraintName?: string;
}

const SelectionPanel = memo(function SelectionPanel({
  position,
  currentValue,
  onSelect,
  onWrap,
  onClose,
  panelRef,
  constraintTypes,
  allowedWrappers,
  constraintName,
}: SelectionPanelProps) {
  const [search, setSearch] = useState('');
  const [showConstraints, setShowConstraints] = useState(true);
  const [showTypes, setShowTypes] = useState(true);
  const [useRegex, setUseRegex] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const { buildableTypes, constraintDefs, getConstraintElements } = useTypeConstraintStore();

  // 是否有约束限制
  const hasConstraint = hasConstraintLimit(constraintTypes, constraintName);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // 使用 service 计算类型分组
  const typeGroups = useMemo(() => {
    const filter: SearchFilter = { searchText: search, showConstraints, showTypes, useRegex };
    const data = { 
      analysis: { 
        isUnconstrained: !hasConstraint, 
        isCompositeConstraint: false, 
        allowedWrappers: null, 
        scalarTypes: constraintTypes 
      }, 
      allowedWrappers, 
      constraintTypes 
    };
    return computeTypeGroups(
      data,
      filter,
      constraintName,
      buildableTypes,
      constraintDefs,
      getConstraintElements
    );
  }, [hasConstraint, constraintTypes, constraintName, constraintDefs, buildableTypes, 
      search, showConstraints, showTypes, useRegex, getConstraintElements, allowedWrappers]);

  const totalCount = useMemo(() =>
    typeGroups.reduce((sum, g) => sum + g.items.length, 0),
    [typeGroups]
  );

  return createPortal(
    <div
      ref={panelRef}
      className="fixed w-72 bg-gray-800 border border-gray-600 rounded shadow-xl"
      style={{ top: position.top, left: position.left, zIndex: 10000 }}
      onMouseDown={e => e.stopPropagation()}
    >
      {/* 搜索栏 */}
      <div className="p-2 border-b border-gray-700">
        <div className="flex items-center gap-1 bg-gray-700 rounded px-2 py-1">
          <input
            ref={inputRef}
            type="text"
            className="flex-1 text-xs bg-transparent focus:outline-none text-gray-200"
            placeholder="搜索..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            onKeyDown={e => e.key === 'Escape' && onClose()}
          />
          {/* 只在无约束时显示过滤按钮 */}
          {!hasConstraint && (
            <div className="flex gap-0.5 border-l border-gray-600 pl-1">
              <button
                type="button"
                className={`w-5 h-5 text-xs rounded ${showConstraints ? 'bg-blue-600 text-white' : 'text-gray-500'}`}
                onClick={() => setShowConstraints(v => !v)}
                title="约束"
              >C</button>
              <button
                type="button"
                className={`w-5 h-5 text-xs rounded ${showTypes ? 'bg-blue-600 text-white' : 'text-gray-500'}`}
                onClick={() => setShowTypes(v => !v)}
                title="类型"
              >T</button>
              <button
                type="button"
                className={`w-5 h-5 text-xs rounded ${useRegex ? 'bg-blue-600 text-white' : 'text-gray-500'}`}
                onClick={() => setUseRegex(v => !v)}
                title="正则"
              >.*</button>
            </div>
          )}
        </div>
      </div>

      {/* 包装选项 - 只在有允许的包装器时显示 */}
      {allowedWrappers.length > 0 && (
        <div className="px-2 py-1.5 border-b border-gray-700">
          <div className="text-xs text-gray-500 mb-1">包装为:</div>
          <div className="flex flex-wrap gap-1">
            {allowedWrappers.map(w => (
              <button
                key={w.name}
                type="button"
                className="text-xs px-1.5 py-0.5 rounded bg-gray-700 text-purple-400 hover:bg-gray-600"
                onClick={() => onWrap(w.name)}
              >
                +{w.name}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* 列表 */}
      <div className="max-h-52 overflow-y-auto">
        {totalCount === 0 ? (
          <div className="p-3 text-xs text-gray-500 text-center">无匹配结果</div>
        ) : (
          typeGroups.map((group) => (
            <div key={group.label}>
              {/* 有约束时只有一个分组，不显示标签 */}
              {!(hasConstraint && typeGroups.length === 1) && (
                <div className="px-2 py-1 text-xs text-gray-500 bg-gray-900 sticky top-0">
                  {group.label}
                </div>
              )}
              {group.items.map(item => {
                const color = getTypeColor(item);
                return (
                  <button
                    key={item}
                    type="button"
                    className={`w-full text-left px-3 py-1 text-xs hover:bg-gray-700
                      ${item === currentValue ? 'bg-gray-700' : ''}`}
                    style={{ color }}
                    onClick={() => onSelect(item)}
                  >
                    {item}
                  </button>
                );
              })}
            </div>
          ))
        )}
      </div>

      <div className="px-2 py-1 text-xs text-gray-500 border-t border-gray-700">
        {totalCount} 个结果
      </div>
    </div>,
    document.body
  );
});

// ============ Shape 编辑器 ============

const ShapeEditor = memo(function ShapeEditor({
  shape,
  onChange,
}: {
  shape: (number | null)[];
  onChange: (shape: (number | null)[]) => void;
}) {
  return (
    <span className="inline-flex items-center gap-0.5">
      {shape.map((d, i) => (
        <span key={i} className="inline-flex items-center">
          {i > 0 && <span className="text-gray-500">×</span>}
          <span className="relative group">
            <input
              type="text"
              className="w-6 text-xs bg-gray-700 rounded px-0.5 py-0.5 border border-gray-600
                focus:outline-none focus:border-blue-500 text-gray-200 text-center"
              value={d === null ? '?' : d}
              onChange={e => {
                const val = e.target.value;
                const newShape = [...shape];
                newShape[i] = val === '?' || val === '' ? null : (parseInt(val, 10) || null);
                onChange(newShape);
              }}
              onMouseDown={e => e.stopPropagation()}
            />
            {shape.length > 1 && (
              <button
                type="button"
                className="absolute -top-1 -right-1 w-3 h-3 bg-red-600 rounded-full text-white 
                  text-[8px] opacity-0 group-hover:opacity-100"
                onClick={() => onChange(shape.filter((_, j) => j !== i))}
              >×</button>
            )}
          </span>
        </span>
      ))}
      <button
        type="button"
        className="w-4 h-4 text-[10px] bg-gray-700 hover:bg-gray-600 rounded text-gray-400"
        onClick={() => onChange([...shape, 4])}
      >+</button>
      <span className="text-gray-500">×</span>
    </span>
  );
});

// ============ 构建面板（递归渲染类型结构）============

interface BuildPanelProps {
  node: TypeNode;
  onChange: (node: TypeNode) => void;
  onOpenSelector: (target: 'leaf', rect: DOMRect, currentValue: string, element: Element) => void;
  path?: string;
}

const BuildPanel = memo(function BuildPanel({
  node,
  onChange,
  onOpenSelector,
  path = 'root',
}: BuildPanelProps) {
  const leafRef = useRef<HTMLButtonElement>(null);

  const handleLeafClick = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    if (leafRef.current) {
      const rect = leafRef.current.getBoundingClientRect();
      onOpenSelector('leaf', rect, node.kind === 'scalar' ? node.name : '', leafRef.current);
    }
  }, [node, onOpenSelector]);

  const handleUnwrap = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    if (node.kind === 'composite') {
      onChange(node.element);
    }
  }, [node, onChange]);

  const handleShapeChange = useCallback((shape: (number | null)[]) => {
    if (node.kind === 'composite') {
      onChange({ ...node, shape });
    }
  }, [node, onChange]);

  const handleElementChange = useCallback((element: TypeNode) => {
    if (node.kind === 'composite') {
      onChange({ ...node, element });
    }
  }, [node, onChange]);

  if (node.kind === 'scalar') {
    const color = getTypeColor(node.name);
    return (
      <button
        ref={leafRef}
        type="button"
        className="text-xs bg-gray-700 hover:bg-gray-600 rounded px-1.5 py-0.5 
          border border-gray-600 inline-flex items-center gap-1"
        style={{ color }}
        onClick={handleLeafClick}
      >
        {node.name}
        <span className="text-gray-500 text-[10px]">▼</span>
      </button>
    );
  }

  // 复合类型
  const w = WRAPPERS.find(x => x.name === node.wrapper);

  return (
    <span className="inline-flex items-center flex-wrap gap-0.5">
      <span className="inline-flex items-center group">
        <span className="text-purple-400">{node.wrapper}</span>
        <span className="text-gray-500">&lt;</span>
        <button
          type="button"
          className="w-3 h-3 text-[8px] bg-red-600 rounded text-white ml-0.5
            opacity-0 group-hover:opacity-100"
          onClick={handleUnwrap}
          title="移除此层"
        >×</button>
      </span>

      {w?.hasShape && node.shape && (
        <ShapeEditor shape={node.shape} onChange={handleShapeChange} />
      )}

      <BuildPanel
        node={node.element}
        onChange={handleElementChange}
        onOpenSelector={onOpenSelector}
        path={`${path}.element`}
      />

      <span className="text-gray-500">&gt;</span>
    </span>
  );
});

// ============ 主组件 ============

interface UnifiedTypeSelectorProps {
  selectedType: string;
  onTypeSelect: (type: string) => void;
  /** 
   * 可选约束，限制可选类型范围
   * - 无约束或 AnyType：显示所有约束和类型，允许构建任意复合类型
   * - 标量约束（如 SignlessIntegerLike）：只显示匹配的标量类型
   * - 复合类型约束（如 AnyTensor）：允许构建对应的复合类型
   */
  constraint?: string;
  /** 
   * 允许的具体类型列表（来自后端 AnyTypeOf 解析）
   * 如果提供，优先使用此列表而非从 constraintMap 查找
   */
  allowedTypes?: string[];
  /** 显示名称（用于 tooltip） */
  displayName?: string;
  /** 描述（用于 tooltip） */
  description?: string;
  disabled?: boolean;
  className?: string;
}

export const UnifiedTypeSelector = memo(function UnifiedTypeSelector({
  selectedType,
  onTypeSelect,
  constraint,
  allowedTypes: propAllowedTypes,
  disabled = false,
  className = '',
}: UnifiedTypeSelectorProps) {
  const { 
    buildableTypes, 
    constraintDefs, 
    getConstraintElements, 
    isShapedConstraint, 
    getAllowedContainers 
  } = useTypeConstraintStore();

  // 使用 service 计算数据
  const selectorData = useMemo(() => 
    computeTypeSelectorData({
      constraint,
      allowedTypes: propAllowedTypes,
      buildableTypes,
      constraintDefs,
      getConstraintElements,
      isShapedConstraint,
      getAllowedContainers,
    }),
    [constraint, propAllowedTypes, buildableTypes, constraintDefs, 
     getConstraintElements, isShapedConstraint, getAllowedContainers]
  );

  const { allowedWrappers, constraintTypes } = selectorData;

  const [isOpen, setIsOpen] = useState(false);
  const [selectorPos, setSelectorPos] = useState({ top: 0, left: 0 });
  // node 完全由 selectedType 派生（受控模式），无需本地 state
  const node = useMemo(() => parseType(selectedType || 'AnyType'), [selectedType]);
  const containerRef = useRef<HTMLDivElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const clickedElementRef = useRef<Element | null>(null);

  // 更新位置（RAF 循环）- 跟随点击的元素
  useEffect(() => {
    if (!isOpen) return;

    let rafId: number;
    const update = () => {
      const el = clickedElementRef.current;
      if (el && document.body.contains(el)) {
        const rect = el.getBoundingClientRect();
        setSelectorPos({ top: rect.bottom + 4, left: rect.left });
      }
      rafId = requestAnimationFrame(update);
    };
    rafId = requestAnimationFrame(update);
    return () => cancelAnimationFrame(rafId);
  }, [isOpen]);

  // 点击外部关闭
  useEffect(() => {
    if (!isOpen) return;
    const handler = (e: MouseEvent) => {
      const target = e.target as Node;
      // 检查是否点击在容器或面板内
      if (containerRef.current?.contains(target)) return;
      if (panelRef.current?.contains(target)) return;
      setIsOpen(false);
    };
    // 使用 capture 阶段，确保在其他处理器之前执行
    document.addEventListener('mousedown', handler, true);
    return () => document.removeEventListener('mousedown', handler, true);
  }, [isOpen]);

  const handleOpenSelector = useCallback((_target: 'leaf', rect: DOMRect, _currentValue: string, element: Element) => {
    clickedElementRef.current = element;
    setSelectorPos({ top: rect.bottom + 4, left: rect.left });
    setIsOpen(true);
  }, []);

  const handleSelect = useCallback((value: string) => {
    // 找到最内层的 scalar 并替换
    const updateLeaf = (n: TypeNode): TypeNode => {
      if (n.kind === 'scalar') {
        return { kind: 'scalar', name: value };
      }
      return { ...n, element: updateLeaf(n.element) };
    };
    const newNode = updateLeaf(node);
    onTypeSelect(serializeType(newNode));
    setIsOpen(false);
  }, [node, onTypeSelect]);

  const handleWrap = useCallback((wrapper: string) => {
    // 包装最内层的 scalar，而不是整个 node
    const wrapLeaf = (n: TypeNode): TypeNode => {
      if (n.kind === 'scalar') {
        return wrapWith(n, wrapper);
      }
      return { ...n, element: wrapLeaf(n.element) };
    };
    const newNode = wrapLeaf(node);
    onTypeSelect(serializeType(newNode));
    setIsOpen(false);
  }, [node, onTypeSelect]);

  const handleNodeChange = useCallback((newNode: TypeNode) => {
    onTypeSelect(serializeType(newNode));
  }, [onTypeSelect]);

  const preview = useMemo(() => serializeType(node), [node]);
  const color = getTypeColor(node.kind === 'scalar' ? node.name : 'tensor');

  // 禁用时显示为只读
  if (disabled) {
    return (
      <span
        className={`text-xs px-1.5 py-0.5 rounded ${className}`}
        style={{ color, backgroundColor: `${color}20`, border: `1px solid ${color}40` }}
      >
        {preview}
      </span>
    );
  }

  return (
    <>
      <div
        ref={containerRef}
        className={`inline-flex items-center gap-1 bg-gray-800 rounded px-2 py-1 
          border border-gray-600 ${className}`}
        onMouseDown={e => e.stopPropagation()}
      >
        <BuildPanel
          node={node}
          onChange={handleNodeChange}
          onOpenSelector={handleOpenSelector}
        />
      </div>

      {isOpen && (
        <SelectionPanel
          position={selectorPos}
          currentValue={node.kind === 'scalar' ? node.name : ''}
          onSelect={handleSelect}
          onWrap={handleWrap}
          onClose={() => setIsOpen(false)}
          panelRef={panelRef}
          constraintTypes={constraintTypes}
          allowedWrappers={allowedWrappers}
          constraintName={constraint}
        />
      )}
    </>
  );
});

export default UnifiedTypeSelector;

// frontend/src/editor/adapters/vueflow/components/UnifiedTypeSelector.vue
<!--
  UnifiedTypeSelector.vue - 统一类型选择器 (Vue 版本)
  
  对齐 React Flow 的 UnifiedTypeSelector.tsx 功能：
  1. 构建面板始终可见：显示当前类型结构，支持嵌套可视化
  2. 选择面板复用：点击任意可编辑部分（▼）时显示同一个选择器
  3. 约束类型支持：AnyType、AnyFloat 等约束可作为类型使用
  4. 包装选项统一：在选择面板中提供 +tensor、+vector 等包装入口
  5. 方言分组：内置约束/类型 + 方言
  
  数据逻辑使用 typeSelectorService.ts，本组件只负责渲染
-->
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, nextTick, defineComponent, h } from 'vue';
import { getTypeColor } from '../../../../services/typeSystem';
import {
  type TypeNode,
  WRAPPERS,
  serializeType,
  parseType,
  wrapWith,
} from '../../../../services/typeNodeUtils';
import {
  type SearchFilter,
  computeTypeSelectorData,
  computeTypeGroups,
  hasConstraintLimit,
} from '../../../../services/typeSelectorService';

// ============ Props & Emits ============

const props = defineProps<{
  selectedType: string;
  constraint?: string;
  allowedTypes?: string[];
  disabled?: boolean;
}>();

const emit = defineEmits<{
  (e: 'select', type: string): void;
}>();

// ============ Store (使用 Vue Adapter) ============

import { getStoreSnapshot, typeConstraintStore } from '../../../../stores';

// 使用 getStoreSnapshot 获取静态数据（typeConstraintStore 数据不常变化）
function getTypeConstraintStore() {
  return getStoreSnapshot(typeConstraintStore, (s) => ({
    buildableTypes: s.buildableTypes,
    constraintDefs: s.constraintDefs,
    getConstraintElements: s.getConstraintElements,
    isShapedConstraint: s.isShapedConstraint,
    getAllowedContainers: s.getAllowedContainers,
  }));
}

// ============ 状态 ============

const isOpen = ref(false);
const selectorPos = ref({ top: 0, left: 0 });
const search = ref('');
const showConstraints = ref(true);
const showTypes = ref(true);
const useRegex = ref(false);

const containerRef = ref<HTMLDivElement | null>(null);
const panelRef = ref<HTMLDivElement | null>(null);
const searchInputRef = ref<HTMLInputElement | null>(null);
const clickedElement = ref<Element | null>(null);

// ============ 计算属性 ============

// 解析当前类型为 TypeNode
const node = computed(() => parseType(props.selectedType || 'AnyType'));

// 使用 service 计算选择器数据
const selectorData = computed(() => {
  const store = getTypeConstraintStore();
  return computeTypeSelectorData({
    constraint: props.constraint,
    allowedTypes: props.allowedTypes,
    buildableTypes: store.buildableTypes,
    constraintDefs: store.constraintDefs,
    getConstraintElements: store.getConstraintElements,
    isShapedConstraint: store.isShapedConstraint,
    getAllowedContainers: store.getAllowedContainers,
  });
});

// 是否有约束限制
const hasConstraint = computed(() => 
  hasConstraintLimit(selectorData.value.constraintTypes, props.constraint)
);

// 搜索过滤器
const filter = computed<SearchFilter>(() => ({
  searchText: search.value,
  showConstraints: showConstraints.value,
  showTypes: showTypes.value,
  useRegex: useRegex.value,
}));

// 类型分组
const typeGroups = computed(() => {
  const store = getTypeConstraintStore();
  return computeTypeGroups(
    selectorData.value,
    filter.value,
    props.constraint,
    store.buildableTypes,
    store.constraintDefs,
    store.getConstraintElements
  );
});

// 总数
const totalCount = computed(() => 
  typeGroups.value.reduce((sum, g) => sum + g.items.length, 0)
);

// 预览文本
const preview = computed(() => serializeType(node.value));

// 颜色
const color = computed(() => 
  getTypeColor(node.value.kind === 'scalar' ? node.value.name : 'tensor')
);

// 当前叶子节点值
const currentLeafValue = computed(() => 
  node.value.kind === 'scalar' ? node.value.name : ''
);

// ============ 方法 ============

function openSelector(rect: DOMRect, element: Element) {
  clickedElement.value = element;
  selectorPos.value = { top: rect.bottom + 4, left: rect.left };
  isOpen.value = true;
  search.value = '';
  nextTick(() => {
    searchInputRef.value?.focus();
  });
}

function closeSelector() {
  isOpen.value = false;
}

function handleSelect(value: string) {
  // 找到最内层的 scalar 并替换
  const updateLeaf = (n: TypeNode): TypeNode => {
    if (n.kind === 'scalar') {
      return { kind: 'scalar', name: value };
    }
    return { ...n, element: updateLeaf(n.element) };
  };
  const newNode = updateLeaf(node.value);
  emit('select', serializeType(newNode));
  closeSelector();
}

function handleWrap(wrapper: string) {
  // 包装最内层的 scalar
  const wrapLeaf = (n: TypeNode): TypeNode => {
    if (n.kind === 'scalar') {
      return wrapWith(n, wrapper);
    }
    return { ...n, element: wrapLeaf(n.element) };
  };
  const newNode = wrapLeaf(node.value);
  emit('select', serializeType(newNode));
  closeSelector();
}

function handleUnwrap(n: TypeNode) {
  if (n.kind === 'composite') {
    // 需要找到父节点并替换
    // 简化处理：直接用 element 替换整个 node
    emit('select', serializeType(n.element));
  }
}

function handleShapeChange(n: TypeNode, newShape: (number | null)[]) {
  if (n.kind === 'composite') {
    const updateShape = (current: TypeNode, target: TypeNode): TypeNode => {
      if (current === target && current.kind === 'composite') {
        return { ...current, shape: newShape };
      }
      if (current.kind === 'composite') {
        return { ...current, element: updateShape(current.element, target) };
      }
      return current;
    };
    const newNode = updateShape(node.value, n);
    emit('select', serializeType(newNode));
  }
}

function handleShapeDimChange(n: TypeNode, index: number, value: string) {
  if (n.kind === 'composite' && n.shape) {
    const newShape = [...n.shape];
    newShape[index] = value === '?' || value === '' ? null : (parseInt(value, 10) || null);
    handleShapeChange(n, newShape);
  }
}

function handleShapeDimRemove(n: TypeNode, index: number) {
  if (n.kind === 'composite' && n.shape && n.shape.length > 1) {
    const newShape = n.shape.filter((_, i) => i !== index);
    handleShapeChange(n, newShape);
  }
}

function handleShapeDimAdd(n: TypeNode) {
  if (n.kind === 'composite') {
    const newShape = [...(n.shape || []), 4];
    handleShapeChange(n, newShape);
  }
}

// ============ 位置跟随 ============

let rafId: number | null = null;

function updatePosition() {
  if (!isOpen.value) return;
  const el = clickedElement.value;
  if (el && document.body.contains(el)) {
    const rect = el.getBoundingClientRect();
    selectorPos.value = { top: rect.bottom + 4, left: rect.left };
  }
  rafId = requestAnimationFrame(updatePosition);
}

watch(isOpen, (open) => {
  if (open) {
    rafId = requestAnimationFrame(updatePosition);
  } else if (rafId !== null) {
    cancelAnimationFrame(rafId);
    rafId = null;
  }
});

// ============ 点击外部关闭 ============

function handleClickOutside(event: MouseEvent) {
  if (!isOpen.value) return;
  const target = event.target as Node;
  if (containerRef.value?.contains(target)) return;
  if (panelRef.value?.contains(target)) return;
  closeSelector();
}

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside, true);
});

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside, true);
  if (rafId !== null) {
    cancelAnimationFrame(rafId);
  }
});

// ============ 递归组件：渲染 TypeNode ============

const BuildNode = defineComponent({
  name: 'BuildNode',
  props: {
    node: { type: Object as () => TypeNode, required: true },
  },
  emits: ['open-selector', 'unwrap', 'shape-dim-change', 'shape-dim-remove', 'shape-dim-add'],
  setup(nodeProps, { emit: nodeEmit }) {
    const leafRef = ref<HTMLButtonElement | null>(null);

    const handleLeafClick = (e: MouseEvent) => {
      e.stopPropagation();
      if (leafRef.value) {
        const rect = leafRef.value.getBoundingClientRect();
        nodeEmit('open-selector', rect, leafRef.value);
      }
    };

    return () => {
      const n = nodeProps.node;

      if (n.kind === 'scalar') {
        const c = getTypeColor(n.name);
        return h('button', {
          ref: leafRef,
          type: 'button',
          class: 'text-xs bg-gray-700 hover:bg-gray-600 rounded px-1.5 py-0.5 border border-gray-600 inline-flex items-center gap-1',
          style: { color: c },
          onClick: handleLeafClick,
        }, [
          n.name,
          h('span', { class: 'text-gray-500 text-[10px]' }, '▼'),
        ]);
      }

      // 复合类型
      const w = WRAPPERS.find(x => x.name === n.wrapper);
      const children: ReturnType<typeof h>[] = [];

      // wrapper<
      children.push(
        h('span', { class: 'inline-flex items-center group' }, [
          h('span', { class: 'text-purple-400' }, n.wrapper),
          h('span', { class: 'text-gray-500' }, '<'),
          h('button', {
            type: 'button',
            class: 'w-3 h-3 text-[8px] bg-red-600 rounded text-white ml-0.5 opacity-0 group-hover:opacity-100',
            title: '移除此层',
            onClick: (e: MouseEvent) => {
              e.stopPropagation();
              nodeEmit('unwrap', n);
            },
          }, '×'),
        ])
      );

      // shape
      if (w?.hasShape && n.shape) {
        const shapeChildren: ReturnType<typeof h>[] = [];
        n.shape.forEach((d, i) => {
          if (i > 0) {
            shapeChildren.push(h('span', { class: 'text-gray-500' }, '×'));
          }
          shapeChildren.push(
            h('span', { class: 'relative group' }, [
              h('input', {
                type: 'text',
                class: 'w-6 text-xs bg-gray-700 rounded px-0.5 py-0.5 border border-gray-600 focus:outline-none focus:border-blue-500 text-gray-200 text-center',
                value: d === null ? '?' : d,
                onInput: (e: Event) => {
                  const val = (e.target as HTMLInputElement).value;
                  nodeEmit('shape-dim-change', n, i, val);
                },
                onMousedown: (e: MouseEvent) => e.stopPropagation(),
              }),
              n.shape!.length > 1 ? h('button', {
                type: 'button',
                class: 'absolute -top-1 -right-1 w-3 h-3 bg-red-600 rounded-full text-white text-[8px] opacity-0 group-hover:opacity-100',
                onClick: () => nodeEmit('shape-dim-remove', n, i),
              }, '×') : null,
            ])
          );
        });
        shapeChildren.push(
          h('button', {
            type: 'button',
            class: 'w-4 h-4 text-[10px] bg-gray-700 hover:bg-gray-600 rounded text-gray-400',
            onClick: () => nodeEmit('shape-dim-add', n),
          }, '+')
        );
        shapeChildren.push(h('span', { class: 'text-gray-500' }, '×'));
        children.push(h('span', { class: 'inline-flex items-center gap-0.5' }, shapeChildren));
      }

      // element (递归)
      children.push(
        h(BuildNode, {
          node: n.element,
          'onOpen-selector': (rect: DOMRect, el: Element) => nodeEmit('open-selector', rect, el),
          onUnwrap: (node: TypeNode) => nodeEmit('unwrap', node),
          'onShape-dim-change': (node: TypeNode, i: number, v: string) => nodeEmit('shape-dim-change', node, i, v),
          'onShape-dim-remove': (node: TypeNode, i: number) => nodeEmit('shape-dim-remove', node, i),
          'onShape-dim-add': (node: TypeNode) => nodeEmit('shape-dim-add', node),
        })
      );

      // >
      children.push(h('span', { class: 'text-gray-500' }, '>'));

      return h('span', { class: 'inline-flex items-center flex-wrap gap-0.5' }, children);
    };
  },
});
</script>

<template>
  <!-- 禁用状态 -->
  <span
    v-if="disabled"
    class="text-xs px-1.5 py-0.5 rounded"
    :style="{ 
      color, 
      backgroundColor: `${color}20`, 
      border: `1px solid ${color}40` 
    }"
  >
    {{ preview }}
  </span>

  <!-- 正常状态 -->
  <template v-else>
    <div
      ref="containerRef"
      class="inline-flex items-center gap-1 bg-gray-800 rounded px-2 py-1 border border-gray-600"
      @mousedown.stop
    >
      <!-- 递归渲染 TypeNode -->
      <BuildNode 
        :node="node"
        @open-selector="openSelector"
        @unwrap="handleUnwrap"
        @shape-dim-change="handleShapeDimChange"
        @shape-dim-remove="handleShapeDimRemove"
        @shape-dim-add="handleShapeDimAdd"
      />
    </div>

    <!-- 选择面板 -->
    <Teleport to="body">
      <div
        v-if="isOpen"
        ref="panelRef"
        class="fixed w-72 bg-gray-800 border border-gray-600 rounded shadow-xl"
        :style="{ top: selectorPos.top + 'px', left: selectorPos.left + 'px', zIndex: 10000 }"
        @mousedown.stop
      >
        <!-- 搜索栏 -->
        <div class="p-2 border-b border-gray-700">
          <div class="flex items-center gap-1 bg-gray-700 rounded px-2 py-1">
            <input
              ref="searchInputRef"
              v-model="search"
              type="text"
              class="flex-1 text-xs bg-transparent focus:outline-none text-gray-200"
              placeholder="搜索..."
              @keydown.esc="closeSelector"
            />
            <!-- 只在无约束时显示过滤按钮 -->
            <div v-if="!hasConstraint" class="flex gap-0.5 border-l border-gray-600 pl-1">
              <button
                type="button"
                class="w-5 h-5 text-xs rounded"
                :class="showConstraints ? 'bg-blue-600 text-white' : 'text-gray-500'"
                title="约束"
                @click="showConstraints = !showConstraints"
              >C</button>
              <button
                type="button"
                class="w-5 h-5 text-xs rounded"
                :class="showTypes ? 'bg-blue-600 text-white' : 'text-gray-500'"
                title="类型"
                @click="showTypes = !showTypes"
              >T</button>
              <button
                type="button"
                class="w-5 h-5 text-xs rounded"
                :class="useRegex ? 'bg-blue-600 text-white' : 'text-gray-500'"
                title="正则"
                @click="useRegex = !useRegex"
              >.*</button>
            </div>
          </div>
        </div>

        <!-- 包装选项 -->
        <div v-if="selectorData.allowedWrappers.length > 0" class="px-2 py-1.5 border-b border-gray-700">
          <div class="text-xs text-gray-500 mb-1">包装为:</div>
          <div class="flex flex-wrap gap-1">
            <button
              v-for="w in selectorData.allowedWrappers"
              :key="w.name"
              type="button"
              class="text-xs px-1.5 py-0.5 rounded bg-gray-700 text-purple-400 hover:bg-gray-600"
              @click="handleWrap(w.name)"
            >
              +{{ w.name }}
            </button>
          </div>
        </div>

        <!-- 列表 -->
        <div class="max-h-52 overflow-y-auto">
          <div v-if="totalCount === 0" class="p-3 text-xs text-gray-500 text-center">
            无匹配结果
          </div>
          <template v-else>
            <div v-for="group in typeGroups" :key="group.label">
              <!-- 有约束时只有一个分组，不显示标签 -->
              <div 
                v-if="!(hasConstraint && typeGroups.length === 1)"
                class="px-2 py-1 text-xs text-gray-500 bg-gray-900 sticky top-0"
              >
                {{ group.label }}
              </div>
              <button
                v-for="item in group.items"
                :key="item"
                type="button"
                class="w-full text-left px-3 py-1 text-xs hover:bg-gray-700"
                :class="{ 'bg-gray-700': item === currentLeafValue }"
                :style="{ color: getTypeColor(item) }"
                @click="handleSelect(item)"
              >
                {{ item }}
              </button>
            </div>
          </template>
        </div>

        <div class="px-2 py-1 text-xs text-gray-500 border-t border-gray-700">
          {{ totalCount }} 个结果
        </div>
      </div>
    </Teleport>
  </template>
</template>

<style scoped>
/* 组件样式 */
</style>
