// frontend/src/editor/adapters/vueflow/nodes/FunctionReturnNode.vue
<!--
  FunctionReturn 节点 - 对应 React Flow 的 FunctionReturnNode.tsx
  
  功能：
  - 显示函数返回值作为输入端口
  - 支持添加/删除/重命名返回值
  - 支持类型选择器
  - main 函数隐藏编辑功能
-->
<script setup lang="ts">
import { computed, watch } from 'vue';
import { Handle, Position, useVueFlow } from '@vue-flow/core';
import { getTypeColor } from '../../../../services/typeSystem';
import { 
  useVueStore, 
  projectStore, 
  typeConstraintStore,
  getStoreSnapshot,
} from '../../../../stores';
import { computeTypeSelectorState, type TypeSelectorRenderParams } from '../../../../services/typeSelectorRenderer';
import { dataInHandle } from '../../../../services/port';
import { getContainerStyle, getHeaderStyle, getHandleTop, getCSSVariables, EXEC_COLOR } from './nodeStyles';
import UnifiedTypeSelector from '../components/UnifiedTypeSelector.vue';
import EditableName from '../components/EditableName.vue';
import type { DataPin } from '../../../../types';
import { generateReturnTypeName } from '../../../../services/parameterService';
import { buildReturnDataPins } from '../../../../services/pinUtils';

const props = defineProps<{
  id: string;
  data: Record<string, unknown>;
  selected?: boolean;
}>();

// CSS 变量
const cssVars = getCSSVariables();

// Vue Flow 实例（仅用于获取节点/边信息，不用于更新数据）
const { getNodes, getEdges } = useVueFlow();

// 直接更新 editorStore（数据一份，订阅更新）
import { useEditorStoreUpdate } from '../useEditorStoreUpdate';
const { updateNodeData } = useEditorStoreUpdate(props.id);

// 使用 Vue Store Adapter 订阅 projectStore
const currentFunction = useVueStore(
  projectStore,
  (state) => {
    if (!state.project || !state.currentFunctionId) return null;
    return state.project.mainFunction.id === state.currentFunctionId
      ? state.project.mainFunction
      : state.project.customFunctions.find(f => f.id === state.currentFunctionId) || null;
  }
);

// 基础数据
const branchName = computed(() => (props.data.branchName as string) || '');
const isMain = computed(() => (props.data.isMain as boolean) || false);
const execIn = computed(() => props.data.execIn as { id: string; label: string } | undefined);
const pinnedTypes = computed(() => (props.data.pinnedTypes as Record<string, string>) || {});
const inputTypes = computed(() => (props.data.inputTypes as Record<string, string>) || {});

const functionId = computed(() => currentFunction.value?.id || '');
const returnTypes = computed(() => currentFunction.value?.returnTypes || []);

// 构建 DataPin 列表（使用公用服务）
const dataPins = computed<DataPin[]>(() => {
  return buildReturnDataPins(
    returnTypes.value,
    { pinnedTypes: pinnedTypes.value, inputTypes: inputTypes.value },
    isMain.value
  );
});

// 构建输入引脚（包含执行引脚）
const inputPins = computed(() => {
  const pins: Array<{ id: string; name: string; label: string; isExec: boolean; color: string }> = [];
  
  if (execIn.value) {
    pins.push({ id: execIn.value.id, name: 'exec-in', label: '', isExec: true, color: EXEC_COLOR });
  }
  
  for (const pin of dataPins.value) {
    pins.push({
      id: pin.id,
      name: pin.label,
      label: pin.label,
      isExec: false,
      color: pin.color || getTypeColor(pin.typeConstraint),
    });
  }
  
  return pins;
});

// 同步 FunctionDef.returnTypes 到 editorStore node data.inputs
watch(returnTypes, (newReturns) => {
  if (isMain.value) return;
  
  const newInputs = newReturns.map((ret, idx) => ({
    id: dataInHandle(ret.name || `result_${idx}`),
    name: ret.name || `result_${idx}`,
    kind: 'input' as const,
    typeConstraint: ret.constraint,
    color: getTypeColor(ret.constraint),
  }));
  
  const currentInputs = (props.data.inputs as Array<{ name: string }>) || [];
  const currentNames = currentInputs.map(i => i.name).join(',');
  const newNames = newInputs.map(i => i.name).join(',');
  
  if (currentNames !== newNames) {
    updateNodeData(data => ({ ...data, inputs: newInputs }));
  }
}, { immediate: true });

// 类型选择器参数
function getTypeSelectorParams(_pin: DataPin): TypeSelectorRenderParams {
  const constraintState = getStoreSnapshot(typeConstraintStore, (s) => ({
    getConstraintElements: s.getConstraintElements,
  }));
  
  return {
    nodeId: props.id,
    data: props.data as Record<string, unknown>,
    nodes: getNodes.value.map(n => ({
      id: n.id,
      type: (n.type || 'operation') as 'operation' | 'function-entry' | 'function-return' | 'function-call',
      data: n.data as Record<string, unknown>,
      position: n.position || { x: 0, y: 0 },
    })),
    edges: getEdges.value.map(e => ({
      id: e.id,
      source: e.source,
      target: e.target,
      sourceHandle: e.sourceHandle || '',
      targetHandle: e.targetHandle || '',
    })),
    currentFunction: currentFunction.value ?? undefined,
    getConstraintElements: constraintState.getConstraintElements,
    onTypeSelect: handleTypeSelect,
  };
}

// 类型选择处理 - 直接更新 editorStore
function handleTypeSelect(portId: string, type: string, _originalConstraint: string) {
  updateNodeData(data => ({
    ...data,
    pinnedTypes: { ...(data.pinnedTypes as Record<string, string> || {}), [portId]: type },
  }));
  // TODO: 触发类型传播
}

// 返回值操作（使用公用服务）
function handleAddReturnType() {
  const state = projectStore.getState();
  const func = state.getFunctionById(functionId.value);
  const existingNames = func?.returnTypes.map(r => r.name || '') || [];
  const newName = generateReturnTypeName(existingNames);
  if (functionId.value) {
    state.addReturnType(functionId.value, { name: newName, constraint: 'AnyType' });
  }
}

function handleRemoveReturnType(returnName: string) {
  const state = projectStore.getState();
  if (functionId.value) {
    state.removeReturnType(functionId.value, returnName);
  }
}

function handleRenameReturnType(oldName: string, newName: string) {
  const state = projectStore.getState();
  const func = state.getFunctionById(functionId.value);
  const ret = func?.returnTypes.find(r => r.name === oldName);
  if (ret && functionId.value) {
    state.updateReturnType(functionId.value, oldName, { ...ret, name: newName });
  }
}

// 样式
const containerStyle = computed(() => getContainerStyle(props.selected || false));
const headerColor = computed(() => isMain.value ? '#dc2626' : '#ef4444');
const headerText = computed(() => branchName.value ? `Return "${branchName.value}"` : 'Return');
const headerStyle = computed(() => getHeaderStyle(headerColor.value));
</script>

<template>
  <div class="return-node" :style="{ ...containerStyle, ...cssVars }">
    <div class="node-header" :style="headerStyle">
      <span class="fn-name">{{ headerText }}</span>
      <span v-if="isMain" class="main-tag">(main)</span>
    </div>
    
    <div class="node-body">
      <!-- 执行引脚行 -->
      <div v-if="execIn" class="pin-row">
        <div class="pin-cell left">
          <div class="ml-4" />
        </div>
      </div>
      
      <!-- 数据引脚行 -->
      <div v-for="pin in dataPins" :key="pin.id" class="pin-row group">
        <div class="pin-cell left flex-1">
          <div class="pin-content left">
            <!-- 可编辑名称 -->
            <EditableName
              v-if="!isMain"
              :value="pin.label"
              @change="(n) => handleRenameReturnType(pin.label, n)"
            />
            <span v-else class="pin-label">{{ pin.label }}</span>
            
            <!-- 类型选择器 -->
            <UnifiedTypeSelector
              :selected-type="(() => {
                const params = getTypeSelectorParams(pin);
                const state = computeTypeSelectorState(pin, params);
                return state.displayType;
              })()"
              :constraint="pin.typeConstraint"
              :allowed-types="(() => {
                const params = getTypeSelectorParams(pin);
                const state = computeTypeSelectorState(pin, params);
                return state.options.length > 0 ? state.options : undefined;
              })()"
              :disabled="(() => {
                const params = getTypeSelectorParams(pin);
                const state = computeTypeSelectorState(pin, params);
                return !state.canEdit;
              })()"
              @select="(type) => handleTypeSelect(pin.id, type, pin.typeConstraint)"
            />
          </div>
        </div>
        
        <!-- 删除按钮 -->
        <button
          v-if="!isMain"
          class="delete-btn"
          title="Remove"
          @click="handleRemoveReturnType(pin.label)"
        >
          <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      
      <!-- 添加返回值按钮 -->
      <div v-if="!isMain" class="pin-row">
        <div class="pin-cell left">
          <button class="add-btn" title="Add return value" @click="handleAddReturnType">
            <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
            </svg>
          </button>
        </div>
      </div>
    </div>
    
    <!-- Handles -->
    <Handle
      v-for="(pin, idx) in inputPins"
      :key="pin.id"
      :id="pin.id"
      type="target"
      :position="Position.Left"
      :class="pin.isExec ? 'handle-exec' : 'handle-data'"
      :style="{ top: getHandleTop(idx), backgroundColor: pin.isExec ? 'transparent' : pin.color }"
    />
  </div>
</template>

<style scoped>
.return-node {
  position: relative;
  overflow: visible;
}

.node-header {
  display: flex;
  align-items: center;
  gap: 4px;
}

.fn-name {
  font-size: var(--text-title-size, 14px);
  color: var(--text-title-color, #ffffff);
  font-weight: var(--text-title-weight, 600);
}

.main-tag {
  font-size: var(--text-subtitle-size, 12px);
  color: var(--text-subtitle-color, rgba(255, 255, 255, 0.7));
  margin-left: 4px;
}

.node-body {
  padding: 4px;
}

.pin-row {
  display: flex;
  justify-content: flex-start;
  align-items: center;
  padding: 6px 0;
  min-height: 28px;
  position: relative;
}

.pin-cell {
  position: relative;
  display: flex;
  align-items: center;
}

.pin-cell.left {
  justify-content: flex-start;
}

.pin-content {
  display: flex;
  flex-direction: column;
}

.pin-content.left {
  align-items: flex-start;
  margin-left: 16px;
}

.pin-label {
  font-size: var(--text-label-size, 12px);
  color: var(--text-label-color, #d1d5db);
  line-height: 1;
}

/* 删除按钮 */
.delete-btn {
  opacity: 0;
  padding: 2px;
  color: var(--text-muted-color, #6b7280);
  margin-left: 4px;
  transition: opacity 0.15s;
}

.delete-btn:hover {
  color: var(--btn-danger-hover-color, #f87171);
}

.group:hover .delete-btn {
  opacity: 1;
}

/* 添加按钮 */
.add-btn {
  margin-left: 16px;
  color: var(--text-muted-color, #6b7280);
}

.add-btn:hover {
  color: var(--text-title-color, #ffffff);
}

/* Handle 样式 */
:deep(.handle-exec) {
  width: 0 !important;
  height: 0 !important;
  min-width: 0 !important;
  min-height: 0 !important;
  background: transparent !important;
  border: none !important;
  border-style: solid !important;
  border-width: 5px 0 5px 8px !important;
  border-color: transparent transparent transparent var(--exec-color, #ffffff) !important;
  border-radius: 0 !important;
}

:deep(.handle-data) {
  width: var(--handle-size, 12px) !important;
  height: var(--handle-size, 12px) !important;
  border: 2px solid var(--node-bg-color, #2d2d3d) !important;
  border-radius: 50% !important;
}
</style>

// frontend/src/components/FunctionReturnNode.tsx
/**
 * FunctionReturnNode 组件
 * 
 * 函数返回节点（UE5 风格）：左侧显示 exec-in + 返回值输入
 * 每个 Return 节点可有 branchName 用于多出口函数
 */

import { memo, useCallback, useMemo, useEffect } from 'react';
import { Handle, Position, type NodeProps, type Node, useEdges, useNodes, useReactFlow } from '@xyflow/react';
import type { FunctionReturnData, DataPin } from '../types';
import { getTypeColor } from '../services/typeSystem';
import { useProjectStore } from '../stores/projectStore';
import { useTypeConstraintStore } from '../stores/typeConstraintStore';
import { UnifiedTypeSelector } from './UnifiedTypeSelector';
import { computeTypeSelectorState, type TypeSelectorRenderParams } from '../services/typeSelectorRenderer';
import { EditableName, execPinStyle, dataPinStyle } from './shared';
import { dataInHandle } from '../services/port';
import { useCurrentFunction, useTypeChangeHandler } from '../hooks';

export type FunctionReturnNodeType = Node<FunctionReturnData, 'function-return'>;
export type FunctionReturnNodeProps = NodeProps<FunctionReturnNodeType>;

export const FunctionReturnNode = memo(function FunctionReturnNode({ id, data, selected }: FunctionReturnNodeProps) {
  const { branchName, execIn, isMain, pinnedTypes = {}, inputTypes = {} } = data;
  const edges = useEdges();
  const nodes = useNodes();
  const { setNodes } = useReactFlow();
  const addReturnType = useProjectStore(state => state.addReturnType);
  const removeReturnType = useProjectStore(state => state.removeReturnType);
  const updateReturnType = useProjectStore(state => state.updateReturnType);
  const getFunctionById = useProjectStore(state => state.getFunctionById);
  const getConstraintElements = useTypeConstraintStore(state => state.getConstraintElements);

  const currentFunction = useCurrentFunction();
  const { handleTypeChange } = useTypeChangeHandler({ nodeId: id });

  const functionId = currentFunction?.id || '';

  const handleAddReturnType = useCallback(() => {
    const func = getFunctionById(functionId);
    const existingNames = func?.returnTypes.map(r => r.name || '') || [];
    let index = 0, newName = `ret${index}`;
    while (existingNames.includes(newName)) { index++; newName = `ret${index}`; }
    if (functionId) addReturnType(functionId, { name: newName, constraint: 'AnyType' });
  }, [functionId, addReturnType, getFunctionById]);

  const handleRemoveReturnType = useCallback((returnName: string) => {
    if (functionId) removeReturnType(functionId, returnName);
  }, [functionId, removeReturnType]);

  const handleRenameReturnType = useCallback((oldName: string, newName: string) => {
    const func = getFunctionById(functionId);
    const ret = func?.returnTypes.find(r => r.name === oldName);
    if (ret && functionId) updateReturnType(functionId, oldName, { ...ret, name: newName });
  }, [functionId, updateReturnType, getFunctionById]);

  // 同步 FunctionDef.returnTypes 到 React Flow 节点的 data.inputs
  // 这是为了让类型传播函数能读取到正确的端口列表
  useEffect(() => {
    if (isMain) return;
    
    const returnTypes = currentFunction?.returnTypes || [];
    
    // 构建新的 inputs
    const newInputs = returnTypes.map((ret, idx) => ({
      id: dataInHandle(ret.name || `result_${idx}`),
      name: ret.name || `result_${idx}`,
      kind: 'input' as const,
      typeConstraint: ret.constraint,
      color: getTypeColor(ret.constraint),
    }));
    
    // 检查是否需要更新（避免无限循环）
    const currentNames = (data.inputs || []).map((i: { name: string }) => i.name).join(',');
    const newNames = newInputs.map(i => i.name).join(',');
    
    if (currentNames !== newNames) {
      setNodes(ns => ns.map(n => 
        n.id === id ? { ...n, data: { ...n.data, inputs: newInputs } } : n
      ));
    }
  }, [id, isMain, currentFunction?.returnTypes, data.inputs, setNodes]);

  // 构建 DataPin 列表 - 直接从 FunctionDef.returnTypes 派生（单一数据源）
  const dataPins: DataPin[] = useMemo(() => {
    // main 函数返回固定的 I32，自定义函数从 FunctionDef 读取
    const returns = isMain 
      ? [{ name: 'result', constraint: 'I32' }] 
      : (currentFunction?.returnTypes || []);
    return returns.map((ret, idx) => {
      const name = ret.name || `result_${idx}`;
      const portId = dataInHandle(name);
      const constraint = ret.constraint;
    return {
      id: portId,
        label: name,
      typeConstraint: constraint,
      displayName: constraint,
        color: getTypeColor(inputTypes[name] || pinnedTypes[portId] || constraint),
    };
    });
  }, [isMain, currentFunction?.returnTypes, inputTypes, pinnedTypes]);

  const typeSelectorParams: TypeSelectorRenderParams = useMemo(() => ({
    nodeId: id,
    data,
    nodes,
    edges,
    currentFunction: currentFunction ?? undefined,
    getConstraintElements,
    onTypeSelect: (portId: string, type: string, originalConstraint: string) => {
      handleTypeChange(portId, type, originalConstraint);
    },
  }), [id, data, nodes, edges, currentFunction, getConstraintElements, handleTypeChange]);

  const headerColor = isMain ? '#dc2626' : '#ef4444';
  const headerText = branchName ? `Return "${branchName}"` : 'Return';

  return (
    <div className={`min-w-48 rounded-lg overflow-visible shadow-lg relative ${selected ? 'ring-2 ring-blue-400' : ''}`}
      style={{ backgroundColor: '#2d2d3d', border: `1px solid ${selected ? '#60a5fa' : '#3d3d4d'}` }}>
      <div className="px-3 py-2" style={{ backgroundColor: headerColor }}>
        <span className="text-sm font-semibold text-white">{headerText}</span>
        {isMain && <span className="ml-1 text-xs text-white/70">(main)</span>}
      </div>
      <div className="px-1 py-1">
        <div className="relative flex items-center py-1.5 min-h-7">
          <Handle type="target" position={Position.Left} id={execIn.id} isConnectable={true}
            className="!absolute !left-0 !top-1/2 !-translate-y-1/2 !-translate-x-1/2" style={execPinStyle} />
          <div className="ml-4" />
        </div>
        {dataPins.map((pin) => {
          const { displayType, options, canEdit, onSelect } = computeTypeSelectorState(pin, typeSelectorParams);
          return (
            <div key={pin.id} className="relative flex items-center py-1.5 min-h-7 group">
              <Handle type="target" position={Position.Left} id={pin.id} isConnectable={true}
                className="!absolute !left-0 !top-1/2 !-translate-y-1/2 !-translate-x-1/2"
                style={dataPinStyle(pin.color || getTypeColor(pin.typeConstraint))} />
              <div className="ml-4 flex flex-col items-start flex-1">
                {!isMain ? <EditableName value={pin.label} onChange={(n) => handleRenameReturnType(pin.label, n)} />
                  : <span className="text-xs text-gray-300">{pin.label}</span>}
                <UnifiedTypeSelector 
                  selectedType={displayType}
                  onTypeSelect={onSelect} 
                  constraint={pin.typeConstraint}
                  allowedTypes={options.length > 0 ? options : undefined}
                  disabled={!canEdit} />
              </div>
              {!isMain && <button onClick={() => handleRemoveReturnType(pin.label)}
                className="opacity-0 group-hover:opacity-100 p-0.5 text-gray-500 hover:text-red-400 ml-1" title="Remove">
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
              </button>}
            </div>
          );
        })}
        {!isMain && <div className="relative flex items-center py-1.5 min-h-7">
          <div className="ml-4">
            <button onClick={handleAddReturnType} className="text-gray-500 hover:text-white" title="Add return value">
              <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>
            </button>
          </div>
        </div>}
      </div>
    </div>
  );
});

export default FunctionReturnNode;
